name: flutter_colorpicker
description: A new flutter package project.
version: 0.0.1
author: "fuyumi <fnatic.roach@gmail.com>"
homepage: https://github.com/mchome/flutter_colorpicker

dependencies:
  flutter:
    sdk: flutter

environment:
    sdk: ">=1.8.0 <2.0.0"